# Generated by Django 2.1.7 on 2019-03-07 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_morpheme_type', models.CharField(choices=[('', '선택'), ('mecab', 'mecab'), ('jiana', 'jiana'), ('kkma', 'kkma'), ('komoran', 'komoran'), ('okt', 'okt'), ('hannanum', 'hannanum')], max_length=1)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='files/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['csv'], message='CSV 파일만 허용 가능')])),
            ],
            options={
                'verbose_name': 'csvdocument',
                'verbose_name_plural': 'csvdocuments',
                'db_table': 'morpheme_csvdocument',
            },
        ),
        migrations.CreateModel(
            name='Morpheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'morpheme',
                'verbose_name_plural': 'morphemes',
                'db_table': 'morpheme_morpheme',
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_sentence', models.CharField(max_length=300)),
                ('parsed_sentence', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name': 'sentence',
                'verbose_name_plural': 'sentences',
                'db_table': 'morpheme_sentence',
            },
        ),
    ]
